
func three(d : int, c : int) -> int
{
    let t = 12 + 17 / d;
    17
}

func two(d : int) -> int
{
    three(d, 199);
    assert(0)
}
catch (wrong_array_size)
{
    0
}
catch (index_out_of_bounds)
{
    d + 102
}
catch (division_by_zero)
{
    155
}

func one(d : int) -> int
{
    two(d)
}

func main() -> int
{
    assert(one(0) == 155)
}



